contact_links:
  - name: Support forum
    url: https://musescore.org/en/forum/6
    about: Get help solving a problem or checking if something is a bug in MuseScore Studio.
  - name: Discord server
    url: https://discord.gg/HwHhXEbJ4r
    about: >-
      Ask development questions (programming, translating, etc.) and chat with 
      the MuseScore Studio development team, other contributors, and users.
