name: Build and draft release

# tag and release name format edit id: gen2 below
# result:
# - last commit tagged
# - release draft created (not published yet)

on:
  # schedule: # scheduled workflows will only run on the default branch. edit default values under gen1 and gen2 below
  #   - cron: '0 4 */1 * *' # At 04:00 on every day-of-month
  # push: # push.inputs field does not exist, use gen1 and gen2 below
  #   branches:
  #   - temp32
  # pull_request: # pull_request.inputs field does not exist, edit gen1 below
  workflow_dispatch: # triggered by github web ui run "Build and draft release" workflow button
    inputs:
      manual_name:
        description: 'Release name:'
        default: 'default'
        type: string
        required: true
      manual_tag:
        description: 'Release tag:'
        default: 'default'
        type: string
        required: true
      platforms:
        description: 'Platforms to build:'
        default: 'linux_x64 linux_armhf linux_arm64 macos_intel macos_apple windows_x64 windows_x32 windows_portable_x64 windows_portable_x32'
        type: string
        required: true
      build_mode:
        description: 'Build mode: devel, nightly, testing, stable'
        default: 'devel'
        type: string
        required: true
      runtest:
        description: 'Check: Unit tests (mtests) (in linux yml)'
        default: 'on'
        type: string
        required: false
      runvisualtest:
        description: 'Check: Unit tests (vtest)'
        default: 'on'
        type: string
        required: false
      publish:
        description: 'Publish to FTP when nightly generated (obsolete)'
        default: 'off'
        type: string
        required: true
      notarize:
        description: 'Notarize (in macos yml): on, off'
        default: 'on'
        type: string
        required: true
  # workflow_call: # triggered by "uses" from other yml files.

defaults:
  run:
    shell: bash

jobs:
  plan:
    name: Setup (pub dev yml)
    runs-on: ubuntu-latest
    outputs:
      manual_name: ${{ steps.gen1.outputs.manual_name }}
      manual_tag: ${{ steps.gen1.outputs.manual_tag }}
      platforms: ${{ steps.gen1.outputs.platforms }}
      build_mode: ${{ steps.gen1.outputs.build_mode }}
      runtest: ${{ steps.gen1.outputs.runtest }}
      runvisualtest: ${{ steps.gen1.outputs.runvisualtest }}
      publish: ${{ steps.gen1.outputs.publish }}
      notarize: ${{ steps.gen1.outputs.notarize }}
      execfrom: ${{ steps.gen1.outputs.execfrom }}
    steps:
    - id: gen1
      name: Set or pass values
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]];  then

          echo "triggered by 1. on.pull_request of publishdev or 2. on.pull_request of others that triggers on.workflow_call of publishdev" 

          echo "manual_name=default" | tee -a "$GITHUB_OUTPUT"
          echo "manual_tag=default" | tee -a "$GITHUB_OUTPUT"
          echo "platforms=linux_x64 linux_armhf linux_arm64 macos_intel macos_apple windows_x64 windows_x32 windows_portable_x64 windows_portable_x32" | tee -a "$GITHUB_OUTPUT"
          echo "build_mode=devel" | tee -a "$GITHUB_OUTPUT"  # copied from make_build_mode_env.sh
          echo "runtest=on" | tee -a "$GITHUB_OUTPUT"
          echo "runvisualtest=on" | tee -a "$GITHUB_OUTPUT"
          echo "publish=off" | tee -a "$GITHUB_OUTPUT"
          echo "notarize=off" | tee -a "$GITHUB_OUTPUT"                # pull_request notarize off

        elif [[ "${{ github.event_name }}" == "schedule" ]];  then

          echo "triggered by 1. on.schedule of publishdev or 2. on.schedule of others that triggers on.workflow_call of publishdev" 

          echo "manual_name=default" | tee -a "$GITHUB_OUTPUT"
          echo "manual_tag=default" | tee -a "$GITHUB_OUTPUT"
          echo "platforms=linux_x64 linux_armhf linux_arm64 macos_intel macos_apple windows_x64 windows_x32 windows_portable_x64 windows_portable_x32" | tee -a "$GITHUB_OUTPUT"
          echo "build_mode=nightly" | tee -a "$GITHUB_OUTPUT"  # copied from make_build_mode_env.sh
          echo "runtest=on" | tee -a "$GITHUB_OUTPUT"
          echo "runvisualtest=on" | tee -a "$GITHUB_OUTPUT"
          echo "publish=off" | tee -a "$GITHUB_OUTPUT"
          echo "notarize=on" | tee -a "$GITHUB_OUTPUT"

        elif [[ "${{ github.event_name }}" == "push" ]]; then

          echo "triggered by 1. on.push of publishdev or 2. on.push of others that triggers on.workflow_call of publishdev" 

          echo "manual_name=default" | tee -a "$GITHUB_OUTPUT"
          echo "manual_tag=default" | tee -a "$GITHUB_OUTPUT"
          echo "platforms=linux_x64 linux_armhf linux_arm64 macos_intel macos_apple windows_x64 windows_x32 windows_portable_x64 windows_portable_x32" | tee -a "$GITHUB_OUTPUT"
          echo "build_mode=devel" | tee -a "$GITHUB_OUTPUT"  # copied from make_build_mode_env.sh
          echo "runtest=on" | tee -a "$GITHUB_OUTPUT"
          echo "runvisualtest=on" | tee -a "$GITHUB_OUTPUT"
          echo "publish=off" | tee -a "$GITHUB_OUTPUT"
          echo "notarize=on" | tee -a "$GITHUB_OUTPUT"

          echo "platforms=linux_armhf linux_arm64" | tee -a "$GITHUB_OUTPUT" 
          echo "runtest=off" | tee -a "$GITHUB_OUTPUT"
          echo "runvisualtest=off" | tee -a "$GITHUB_OUTPUT"

        else

          echo "manual_name=${{ inputs.manual_name }}" | tee -a "$GITHUB_OUTPUT"
          echo "manual_tag=${{ inputs.manual_tag }}" | tee -a "$GITHUB_OUTPUT"
          echo "platforms=${{ inputs.platforms }}" | tee -a "$GITHUB_OUTPUT"
          echo "build_mode=${{ inputs.build_mode }}" | tee -a "$GITHUB_OUTPUT"
          echo "runtest=${{ inputs.runtest }}" | tee -a "$GITHUB_OUTPUT"
          echo "runvisualtest=${{ inputs.runvisualtest }}" | tee -a "$GITHUB_OUTPUT"
          echo "publish=${{ inputs.publish }}" | tee -a "$GITHUB_OUTPUT"
          echo "notarize=${{ inputs.notarize }}" | tee -a "$GITHUB_OUTPUT"

        fi

        echo "execfrom=publishdev" | tee -a "$GITHUB_OUTPUT"

  plan2:
    name: Generate release name and tag
    needs:
      - plan
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.gen2.outputs.release_name }}
      release_tag: ${{ steps.gen2.outputs.release_tag }}
      add_tag_to_commit: ${{ steps.gen2.outputs.release_tag }}
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # entire history for all branches and tags
    - id: gen2
      name: Set or pass values 2
      run: |
        if [[ "${{ needs.plan.outputs.manual_name }}" == "default" ]]; then
          echo "release_name=$(git log -1 --format=%cd --date=format:%Y%m%d)" | tee -a "$GITHUB_OUTPUT"
        else
          echo "release_name=${{ needs.plan.outputs.manual_name }}" | tee -a "$GITHUB_OUTPUT"
        fi
        
        if [[ "${{ needs.plan.outputs.manual_tag }}" == "default" ]] ; then
          echo "release_tag=$(git log -1 --format=%cd --date=format:%Y%m%d)" | tee -a "$GITHUB_OUTPUT"
        else
          echo "release_tag=${{ needs.plan.outputs.manual_tag }}" | tee -a "$GITHUB_OUTPUT"
        fi

        add_tag_to_commit=on
        if [[ $(git tag --list "$release_tag") ]]; then
          echo "tag already exists"
          if [[ "$(git tag --points-at $GITHUB_SHA)" != "$release_tag" ]]; then
            echo "tag is not on the latest commit"
            exit 1
          else
            echo "reusing tag"
            add_tag_to_commit=off
          fi
        fi
        echo "add_tag_to_commit=$add_tag_to_commit" | tee -a "$GITHUB_OUTPUT"

  build:
    name: Build
    needs:
      - plan
    uses: ./.github/workflows/build_all.yml
    secrets: inherit
    with:
      platforms: ${{ needs.plan.outputs.platforms }}
      build_mode: ${{ needs.plan.outputs.build_mode }}
      runtest: ${{ needs.plan.outputs.runtest }}
      runvisualtest: ${{ needs.plan.outputs.runvisualtest }}
      publish: ${{ needs.plan.outputs.publish }}
      notarize: ${{ needs.plan.outputs.notarize }}
      execfrom: ${{ needs.plan.outputs.execfrom }}

  create_release:
    name: Create release
    needs:
      - plan
      - build
      - plan2
    if: ${{ ! failure() && ! cancelled() }} # ? meaning of original comment from master ? >> run even if prior jobs were skipped
    runs-on: ubuntu-latest
    environment:
      name: devpublish
      url: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ needs.plan2.outputs.release_tag }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Download and extract artifacts
      uses: actions/download-artifact@v4
      with:
        path: build.artifacts
    - name: Collate release binaries
      run: |
        build/ci/release/collate_release_binaries.sh
    - name: Tag the lastest commit on default branch
      if: needs.plan2.outputs.add_tag_to_commit == 'on'
      run: |
        git tag "${{ needs.plan2.outputs.release_tag }}" "${GITHUB_SHA}"
        git push origin "${{ needs.plan2.outputs.release_tag }}"
    - name: Draft release page
      uses: softprops/action-gh-release@v2
      with: # https://github.com/softprops/action-gh-release?tab=readme-ov-file#inputs
        draft: true
        files: release/*
        name: ${{ needs.plan2.outputs.release_name }}
        tag_name: ${{ needs.plan2.outputs.release_tag }}
        fail_on_unmatched_files: true
        generate_release_notes: false